In [1]:
import pandas as pd
import numpy as np
import re
from pathlib import Path

In [2]:
# merge seasonal data from each month

path_data= Path.cwd().parent/'data/raw'
years = ['2013','2014']
months = ['09','10','11','12','01','02','03','04','05','06','07']
seasons = [years[0]+'_'+month for month in months[0:4]]+[years[1]+'_'+month for month in months[4:]]
df = [pd.read_csv(path_data/f'performance_{date}.csv', low_memory=False) for date in seasons]

seasons,type(df),len(df),type(df[0])

(['2013_09',
  '2013_10',
  '2013_11',
  '2013_12',
  '2014_01',
  '2014_02',
  '2014_03',
  '2014_04',
  '2014_05',
  '2014_06',
  '2014_07'],
 list,
 11,
 pandas.core.frame.DataFrame)

In [30]:
# # merge data from each season

path_data= Path.cwd().parent/'data/raw'
# years = ['13','14','15','16','17','18','19','20','21']
years = ['13','14','15','16','17','18','19','20','21']
seasons = [ years[i]+years[i+1] for i in range(len(years)) if i <len(years)-1]
df = [pd.read_csv(path_data/f'merge_s{season}.csv', low_memory=False) for season in seasons]

In [31]:
df_concat = pd.concat(df,axis=0)

In [32]:
df_concat.shape

(74165, 19)

In [33]:
sum(i.shape[0] for i in df)

74165

In [34]:
df_concat=df_concat.reset_index(drop=True)

In [35]:
# df_concat.to_csv('all_season.csv',index=False)
df_concat.to_csv(path_data/f'all_season.csv',index=False)

In [36]:
# df_csv= pd.read_csv('all_season.csv')
df_csv= pd.read_csv(path_data/f'all_season.csv')

In [37]:
df_csv

,place,horse_no,horse,jockey,trainer,actual_weight,declared_horse_weight,draw,lbw,running_position,finish_time,win_odds,race,class,going,turf,prize,location,date
0,1,10.0,AMAZING ALWAYS(N432),K Teetan,D E Ferraris,125,1126,9,-,6 ...,1:10.37,26,1(1),Class 5 - 1200M - (40-15),GOOD,"TURF - ""A"" Course","HK$ 550,000",Sha Tin,2013/09/08
1,2,9.0,FLYING SUPREME(K226),W M Lai,T K Ng,127,1074,11,1/2,4 ...,1:10.47,14,1(1),Class 5 - 1200M - (40-15),GOOD,"TURF - ""A"" Course","HK$ 550,000",Sha Tin,2013/09/08
2,3,11.0,COSMO ONE(M410),D Whyte,Y S Tsui,123,1030,13,1-3/4,7 ...,1:10.66,4.5,1(1),Class 5 - 1200M - (40-15),GOOD,"TURF - ""A"" Course","HK$ 550,000",Sha Tin,2013/09/08
3,4,6.0,SOUTHERN SPRINGS(P139),K C Leung,C S Shum,126,1107,10,2-1/4,2 ...,1:10.71,31,1(1),Class 5 - 1200M - (40-15),GOOD,"TURF - ""A"" Course","HK$ 550,000",Sha Tin,2013/09/08
4,5,5.0,BERNARD'S CHOICE(N156),Z Purton,P O'Sullivan,128,1044,6,2-1/4,8 ...,1:10.72,4.3,1(1),Class 5 - 1200M - (40-15),GOOD,"TURF - ""A"" Course","HK$ 550,000",Sha Tin,2013/09/08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74160,9,3.0,ARROGANT(D025),C Schofield,C Fownes,130,1065,12,4-3/4,9 ...,1:50.99,19,9(325),Class 3 - 1800M - (80-60),GOOD,"TURF - ""A"" Course","HK$ 1,500,000",Happy Valley,2021/01/06
74161,10,12.0,DIVINE UNICORN(C269),V Borges,W Y So,113,1208,9,5-3/4,7 ...,1:51.18,44,9(325),Class 3 - 1800M - (80-60),GOOD,"TURF - ""A"" Course","HK$ 1,500,000",Happy Valley,2021/01/06
74162,11,6.0,BLASTOISE(C450),A Hamelin,D E Ferraris,128,1096,8,8,4 ...,1:51.52,47,9(325),Class 3 - 1800M - (80-60),GOOD,"TURF - ""A"" Course","HK$ 1,500,000",Happy Valley,2021/01/06
74163,12,11.0,TOYCOON(D203),K C Leung,P F Yiu,119,1033,7,13-1/4,1 ...,1:52.38,17,9(325),Class 3 - 1800M - (80-60),GOOD,"TURF - ""A"" Course","HK$ 1,500,000",Happy Valley,2021/01/06
74164,WV,NaN,EASY GO EASY WIN(B112),C L Chau,D J Whyte,126,---,---,---,---,---,---,9(325),Class 3 - 1800M - (80-60),GOOD,"TURF - ""A"" Course","HK$ 1,500,000",Happy Valley,2021/01/06

In [38]:
df_csv.duplicated().any()

False